name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        REPO_URI="public.ecr.aws/i0h4r7u1/devops_testing"
        docker build ./myapp/ -t $REPO_URI:latest

    - name: Push Docker Image to ECR
      run: |
        REPO_URI="public.ecr.aws/i0h4r7u1/devops_testing"
        docker push $REPO_URI:latest
