name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build_docker_image
      run: docker build ./myapp/ -t sangramviv/web_app_demo:latest 
    - name: push_image_to_docker_hub
      run: |
        docker login -u sangramviv -p ${{secrets.DOCKER_HUB}}
        docker push sangramviv/web_app_demo:latest
